package Acme::CPANLists::Import::PerlAdvent::2000_12_14;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2000/14/] (retrieved on 2016-11-07). Visit the URL for the full contents.",entries=>[{module=>"XML::Grove"}],summary=>"Modules mentioned in Perl Advent Calendar 2000 (day 14)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2000 (day 14)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2000/14/> (retrieved on 2016-11-07). Visit the URL for the full contents.

