#!/usr/bin/env perl

use 5.010;
use strict;
use warnings;
use FindBin '$Bin';

use App::CreateAcmeCPANListsImportModules;
use Perinci::Sub::Util qw(gen_curried_sub);
use Perinci::CmdLine::Any;

gen_curried_sub(
    'App::CreateAcmeCPANListsImportModules::create_acme_cpanlists_import_modules',
    {
        modules => [
            {
                name => '2000',
                url => "http://perladvent.org/2000/",
                extract_urls => [map {"http://perladvent.org/2000/$_/"} 1..25],
                summary => 'Modules mentioned in Perl Advent Calendar 2000',
            },
            {
                name => '2000_12_01',
                summary => "Modules mentioned in Perl Advent Calendar 2000 (day 1)",
                url => "http://perladvent.org/2000/1/",
                add_modules => ['Data::Dumper'],
            },
            {
                name => '2000_12_02',
                summary => "Modules mentioned in Perl Advent Calendar 2000 (day 2)",
                url => "http://perladvent.org/2000/2/",
                add_modules => ['LWP::Simple'],
            },
            {
                name => '2000_12_03',
                summary => "Modules mentioned in Perl Advent Calendar 2000 (day 3)",
                url => "http://perladvent.org/2000/3/",
                add_modules => ['POE::Component::IRC'],
            },
            {
                name => '2000_12_04',
                summary => "Modules mentioned in Perl Advent Calendar 2000 (day 4)",
                url => "http://perladvent.org/2000/4/",
                add_modules => ['Exporter'],
            },
            {
                name => '2000_12_05',
                summary => "Modules mentioned in Perl Advent Calendar 2000 (day 5)",
                url => "http://perladvent.org/2000/5/",
                add_modules => ['Time::Local'],
            },
            {
                name => '2000_12_06',
                summary => "Modules mentioned in Perl Advent Calendar 2000 (day 6)",
                url => "http://perladvent.org/2000/6/",
                add_modules => ['Time::Object'],
            },
            {
                name => '2000_12_07',
                summary => "Modules mentioned in Perl Advent Calendar 2000 (day 7)",
                url => "http://perladvent.org/2000/7/",
                add_modules => ['Tie::Scalar::Timeout'],
            },
            {
                name => '2000_12_08',
                summary => "Modules mentioned in Perl Advent Calendar 2000 (day 8)",
                url => "http://perladvent.org/2000/8/",
                add_modules => ['Tie::HashDefaults'],
            },
            {
                name => '2000_12_09',
                summary => "Modules mentioned in Perl Advent Calendar 2000 (day 9)",
                url => "http://perladvent.org/2000/9/",
                add_modules => ['Crypt::RC4'],
            },
            {
                name => '2000_12_10',
                summary => "Modules mentioned in Perl Advent Calendar 2000 (day 10)",
                url => "http://perladvent.org/2000/10/",
                add_modules => ['GD'],
            },
            {
                name => '2000_12_11',
                summary => "Modules mentioned in Perl Advent Calendar 2000 (day 11)",
                url => "http://perladvent.org/2000/11/",
                add_modules => ['Image::Imlib2'],
            },
            {
                name => '2000_12_12',
                summary => "Modules mentioned in Perl Advent Calendar 2000 (day 12)",
                url => "http://perladvent.org/2000/12/",
                add_modules => ['File::Remote'],
            },
            {
                name => '2000_12_13',
                summary => "Modules mentioned in Perl Advent Calendar 2000 (day 13)",
                url => "http://perladvent.org/2000/13/",
                add_modules => ['XML::Simple'],
            },
            {
                name => '2000_12_14',
                summary => "Modules mentioned in Perl Advent Calendar 2000 (day 14)",
                url => "http://perladvent.org/2000/14/",
                add_modules => ['XML::Grove'],
            },
            {
                name => '2000_12_15',
                summary => "Modules mentioned in Perl Advent Calendar 2000 (day 15)",
                url => "http://perladvent.org/2000/15/",
                add_modules => ['Getopt::Long'],
            },
            {
                name => '2000_12_16',
                summary => "Modules mentioned in Perl Advent Calendar 2000 (day 16)",
                url => "http://perladvent.org/2000/16/",
                add_modules => ['File::Find'],
            },
            {
                name => '2000_12_17',
                summary => "Modules mentioned in Perl Advent Calendar 2000 (day 17)",
                url => "http://perladvent.org/2000/17/",
                add_modules => ['DBI'],
            },
            {
                name => '2000_12_18',
                summary => "Modules mentioned in Perl Advent Calendar 2000 (day 18)",
                url => "http://perladvent.org/2000/18/",
                add_modules => ['Memoize'],
            },
            {
                name => '2000_12_19',
                summary => "Modules mentioned in Perl Advent Calendar 2000 (day 19)",
                url => "http://perladvent.org/2000/19/",
                add_modules => ['Storable'],
            },
            {
                name => '2000_12_20',
                summary => "Modules mentioned in Perl Advent Calendar 2000 (day 20)",
                url => "http://perladvent.org/2000/20/",
                add_modules => ['Inline'],
            },
            {
                name => '2000_12_21',
                summary => "Modules mentioned in Perl Advent Calendar 2000 (day 21)",
                url => "http://perladvent.org/2000/21/",
                add_modules => ['Class::Virtual'],
            },
            {
                name => '2000_12_22',
                summary => "Modules mentioned in Perl Advent Calendar 2000 (day 22)",
                url => "http://perladvent.org/2000/22/",
                add_modules => ['Class::Multimethods'],
            },
            {
                name => '2000_12_23',
                summary => "Modules mentioned in Perl Advent Calendar 2000 (day 23)",
                url => "http://perladvent.org/2000/23/",
                add_modules => ['Symbol::Approx::Sub'],
            },
            {
                name => '2000_12_24',
                summary => "Modules mentioned in Perl Advent Calendar 2000 (day 24)",
                url => "http://perladvent.org/2000/24/",
                add_modules => ['Template'],
            },
            {
                name => '2000_12_25',
                summary => "Modules mentioned in Perl Advent Calendar 2000 (day 25)",
                url => "http://perladvent.org/2000/25/",
                add_modules => ['Date::Christmas'],
            },
        ],
        namespace => 'Acme::CPANLists::Import::PerlAdvent',
        user_agent => 'Mozilla/5.0',
        dist_dir => "$Bin/..",
    },
    'app',
);

Perinci::CmdLine::Any->new(
    url => '/main/app',
    log => 1,
)->run;
